### ISSUE TITLE
Configuration for specific .git repo

### ISSUE THREAD

**Issue by basnijholt** [toobaz/ipynb_output_filter#1]
I work on several different machines where my repo is synced. I don't want to configure all machines separately.

I would like to have the option to clean the `.ipynb` from it's output in just this specific repo.

Could you please provide the settings how I could do this just for one specific repository?

Also, does this work for `v4` ipynb?

I suppose its just:

```
git config core.attributesfile ~/myrepo/.gitattributes
git config filter.dropoutput_ipynb.clean ~/myrepo/script/ipynb_output_filter.py
git config filter.dropoutput_ipynb.smudge cat
```

?

**Comment by toobaz** [comment]
Smart idea.

I expect those commands to work, but I never tested them: I will as soon as I find 5 minutes, and expand the README.

Version 4 ipynb should be supported, yes.

**Comment by toobaz** [comment]
Ahem... took a bit to find those 5 minutes, but the solution is actually pretty simple: you can run those commands as I recommend in the README (so with `--global`) and just keep .gitattributes in the git repo under version control, rather than (or apart from) using a global one (`~/.gitattributes`).
