### ISSUE TITLE
Empty output metadata fields "collapsed" and "scrolled"

### ISSUE THREAD

**Issue by mgab** [toobaz/ipynb_output_filter#11]
Hi,

I have modified the script to reset the "collapsed" fields to false and delete the "scrolled" fields from cell metadata, to avoid detecting uncommited changes if you just collapsed some cells.

I think is not a crazy scenario, but maybe I'm missing how it breaks some other workflow...
I can upload and pull-request the changes if you think it's a good idea.

Thanks for maintaining the repo!

**Comment by toobaz** [comment]
I am not 100% sure we want this. True, "collapsed" and "scrolled" can be annoying in the diffs, but they are not due to the script being run: they are a form of "content". I would gladly accept a PR if it made the choice of stripping such stuff or not configurable in some way... any idea of how to do this?

**Comment by mgab** [comment]
I see your point, but if I'm not missing anything I'd say it shouldn't be a problem here:
As far as I understand, these two properties specify how to display the output of _a code cell_ (raw and markdown cells don't seem to have them defined).
Thus, since the script is removing the outputs anyway, I'd say there is no point in keeping them. I checked and the two properties are reset anyway when the cell is executed, so they have no meaning when the output is empty.

**Comment by toobaz** [comment]
OK, fine then!
